name: Docker Image

on:
  push:

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

      - name: Checkout
        uses: actions/checkout@v4
      - name: Mount Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            root-cache-npm
          key: instance-mount-cache-${{ hashFiles('Dockerfile') }}
      - name: Inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "root-cache-npm": "/root/.npm"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            SOURCE_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  integration_test:
    name: 🚥 Integration test
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: 🚥 Run Container Tests
        uses: docker://gcr.io/gcp-runtimes/container-structure-test:v1.15.0
        with:
          args: test --config container-structure-test.yml --image ghcr.io/${{ github.repository }}:${{ github.sha }} --verbosity debug
