name: Fixtures tests

on:
  push:
    branches:
      - "**"
      - "!master"

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
  NODE_ENV: test
  SYMMETRIC_ENCRYPTION_KEY: aTrueRandom32BytesLongBase64EncodedStringAA=

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      source_database:
        image: postgres:15.10
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      metabase:
        image: postgres:15.10
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: package.json
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - run: npm run build:workspaces
      - run: npm run migrate up
      - run: npm run fixtures:load-ci -- scripts/fixtures.sql
      - run: npm run update-organization-info -- 0
      - run: sh -x scripts/create-anonymized-copy-of-database.sh
        env:
          APP: proconnect-identite
          METABASE_DB_URL: postgresql://postgres:postgres@localhost:5433/postgres
          SCALINGO_POSTGRESQL_URL: ${{ env.DATABASE_URL }}
